class Lang:
    tokens = (
        "NUM",
        "VARIAVEL",
        "STR",
        "FUNCAO",
        "FIM",
        "NAME",
        "ALEATORIO",
        "ESCREVER",
        "INTERPOLATED_STR",
        "ENTRADA",
        "CONCAT",
    )
    literals = (
        "(",
        ")",
        "*",
        "+",
        "=",
        ";",
        '"',
        ",",
        ":",
        "?",
        "!",
        "-",
        "_",
        "{",
        "}",
        "<",
        ">",
        "#",
    )
    t_ignore = " \t"
